"""Auto-generated checkout tests
Generated by Test QA Agent on 2026-07-02T09:54:10.432833
"""
import pytest
from src.utils.logger import logger


@pytest.mark.agent_generated
class TestCheckoutGeneratedTests:

    def test_empty_country_field(self, authenticated_shop_page, cart_page, checkout_page):
        """Generated test: test_empty_country_field"""
        authenticated_shop_page.navigate()
        authenticated_shop_page.add_product_to_cart(authenticated_shop_page.get_product_names()[0])
        authenticated_shop_page.go_to_cart()
        cart_page.proceed_to_checkout()
        assert checkout_page.purchase_btn.is_visible()

    def test_invalid_country_name(self, authenticated_shop_page, cart_page, checkout_page):
        """Generated test: test_invalid_country_name"""
        authenticated_shop_page.navigate()
        authenticated_shop_page.add_product_to_cart(authenticated_shop_page.get_product_names()[0])
        authenticated_shop_page.go_to_cart()
        cart_page.proceed_to_checkout()
        assert checkout_page.purchase_btn.is_visible()

    def test_change_quantity_before_checkout(self, authenticated_shop_page, cart_page, checkout_page):
        """Generated test: test_change_quantity_before_checkout"""
        authenticated_shop_page.navigate()
        authenticated_shop_page.add_product_to_cart(authenticated_shop_page.get_product_names()[0])
        authenticated_shop_page.go_to_cart()
        cart_page.proceed_to_checkout()
        assert checkout_page.purchase_btn.is_visible()

    def test_multiple_items_checkout(self, authenticated_shop_page, cart_page, checkout_page):
        """Generated test: test_multiple_items_checkout"""
        authenticated_shop_page.navigate()
        authenticated_shop_page.add_product_to_cart(authenticated_shop_page.get_product_names()[0])
        authenticated_shop_page.go_to_cart()
        cart_page.proceed_to_checkout()
        assert checkout_page.purchase_btn.is_visible()

    def test_order_confirmation_details(self, authenticated_shop_page, cart_page, checkout_page):
        """Generated test: test_order_confirmation_details"""
        authenticated_shop_page.navigate()
        authenticated_shop_page.add_product_to_cart(authenticated_shop_page.get_product_names()[0])
        authenticated_shop_page.go_to_cart()
        cart_page.proceed_to_checkout()
        assert checkout_page.purchase_btn.is_visible()

    def test_back_to_cart_from_checkout(self, authenticated_shop_page, cart_page, checkout_page):
        """Generated test: test_back_to_cart_from_checkout"""
        authenticated_shop_page.navigate()
        authenticated_shop_page.add_product_to_cart(authenticated_shop_page.get_product_names()[0])
        authenticated_shop_page.go_to_cart()
        cart_page.proceed_to_checkout()
        assert checkout_page.purchase_btn.is_visible()

    def test_purchase_with_special_chars_in_address(self, authenticated_shop_page, cart_page, checkout_page):
        """Generated test: test_purchase_with_special_chars_in_address"""
        authenticated_shop_page.navigate()
        authenticated_shop_page.add_product_to_cart(authenticated_shop_page.get_product_names()[0])
        authenticated_shop_page.go_to_cart()
        cart_page.proceed_to_checkout()
        assert checkout_page.purchase_btn.is_visible()
